steps:
  # まず、依存関係をインストールします
  - name: "node:20" # Node.jsのバージョンはプロジェクトに合わせて調整してください
    entrypoint: "npm"
    args: ["ci"] # より堅牢なインストールには 'ci' を推奨します

  # 次に、テストを実行します
  - name: "node:20"
    entrypoint: "npm"
    args: ["run", "test"] # ここで npm run test を実行！

  # テストが成功したら、Firebaseにデプロイします
  - name: us-docker.pkg.dev/firebase-cli/us/firebase
    args: ["deploy", "--project=${_PROJECT_ID}", "--only=hosting"] # ${_PROJECT_ID} は自動で解決されます
